<?php
// database/seeders/EthiopianFoodItemsSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EthiopianFoodItemsSeeder extends Seeder
{
    public function run(): void
    {
        // Get category IDs
        $categories = DB::table('food_categories')
            ->whereIn('category_name', [
                'Injera & Breads',
                'Wat (Stews)',
                'Tibs',
                'Kitfo',
                'Vegetarian Dishes',
                'Side Dishes',
                'Traditional Breakfast',
                'Beverages',
                'Legume-Based Dishes',
                'Vegetable Dishes',
                'Snacks & Appetizers',
                'Holiday & Special Occasion'
            ])
            ->pluck('category_id', 'category_name');

        $foodItems = [
            // Injera & Breads (15 items)
            [
                'food_name' => 'Teff Injera',
                'brand' => 'Traditional',
                'category_id' => $categories['Injera & Breads'],
                'serving_size' => '1',
                'serving_unit' => 'piece (50g)',
                'calories_per_serving' => 88.0,
                'protein_per_serving' => 3.0,
                'carbs_per_serving' => 18.0,
                'fat_per_serving' => 0.4,
                'fiber_per_serving' => 1.8,
                'sugar_per_serving' => 0.5,
                'sodium_per_serving' => 25.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Barley Injera',
                'brand' => 'Traditional',
                'category_id' => $categories['Injera & Breads'],
                'serving_size' => '1',
                'serving_unit' => 'piece (50g)',
                'calories_per_serving' => 95.0,
                'protein_per_serving' => 3.2,
                'carbs_per_serving' => 19.5,
                'fat_per_serving' => 0.5,
                'fiber_per_serving' => 2.1,
                'sugar_per_serving' => 0.6,
                'sodium_per_serving' => 28.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Wheat Injera',
                'brand' => 'Traditional',
                'category_id' => $categories['Injera & Breads'],
                'serving_size' => '1',
                'serving_unit' => 'piece (50g)',
                'calories_per_serving' => 105.0,
                'protein_per_serving' => 3.8,
                'carbs_per_serving' => 21.0,
                'fat_per_serving' => 0.6,
                'fiber_per_serving' => 1.5,
                'sugar_per_serving' => 0.7,
                'sodium_per_serving' => 30.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Mixed Grain Injera',
                'brand' => 'Traditional',
                'category_id' => $categories['Injera & Breads'],
                'serving_size' => '1',
                'serving_unit' => 'piece (50g)',
                'calories_per_serving' => 98.0,
                'protein_per_serving' => 3.5,
                'carbs_per_serving' => 19.8,
                'fat_per_serving' => 0.5,
                'fiber_per_serving' => 2.0,
                'sugar_per_serving' => 0.6,
                'sodium_per_serving' => 27.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Corn Injera',
                'brand' => 'Traditional',
                'category_id' => $categories['Injera & Breads'],
                'serving_size' => '1',
                'serving_unit' => 'piece (50g)',
                'calories_per_serving' => 110.0,
                'protein_per_serving' => 2.8,
                'carbs_per_serving' => 23.0,
                'fat_per_serving' => 0.9,
                'fiber_per_serving' => 1.8,
                'sugar_per_serving' => 1.2,
                'sodium_per_serving' => 22.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Rice Injera',
                'brand' => 'Traditional',
                'category_id' => $categories['Injera & Breads'],
                'serving_size' => '1',
                'serving_unit' => 'piece (50g)',
                'calories_per_serving' => 92.0,
                'protein_per_serving' => 2.5,
                'carbs_per_serving' => 19.8,
                'fat_per_serving' => 0.3,
                'fiber_per_serving' => 0.8,
                'sugar_per_serving' => 0.4,
                'sodium_per_serving' => 20.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Dabo Kolo',
                'brand' => 'Traditional',
                'category_id' => $categories['Injera & Breads'],
                'serving_size' => '30',
                'serving_unit' => 'pieces (30g)',
                'calories_per_serving' => 120.0,
                'protein_per_serving' => 3.5,
                'carbs_per_serving' => 20.0,
                'fat_per_serving' => 2.5,
                'fiber_per_serving' => 1.2,
                'sugar_per_serving' => 1.0,
                'sodium_per_serving' => 85.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Ambasha',
                'brand' => 'Traditional',
                'category_id' => $categories['Injera & Breads'],
                'serving_size' => '1',
                'serving_unit' => 'slice (60g)',
                'calories_per_serving' => 180.0,
                'protein_per_serving' => 5.5,
                'carbs_per_serving' => 32.0,
                'fat_per_serving' => 3.0,
                'fiber_per_serving' => 1.8,
                'sugar_per_serving' => 5.0,
                'sodium_per_serving' => 220.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Hembesha',
                'brand' => 'Traditional',
                'category_id' => $categories['Injera & Breads'],
                'serving_size' => '1',
                'serving_unit' => 'slice (70g)',
                'calories_per_serving' => 210.0,
                'protein_per_serving' => 6.0,
                'carbs_per_serving' => 35.0,
                'fat_per_serving' => 4.5,
                'fiber_per_serving' => 2.2,
                'sugar_per_serving' => 4.5,
                'sodium_per_serving' => 280.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Defo Dabo',
                'brand' => 'Traditional',
                'category_id' => $categories['Injera & Breads'],
                'serving_size' => '1',
                'serving_unit' => 'slice (80g)',
                'calories_per_serving' => 250.0,
                'protein_per_serving' => 7.0,
                'carbs_per_serving' => 40.0,
                'fat_per_serving' => 5.5,
                'fiber_per_serving' => 2.5,
                'sugar_per_serving' => 8.0,
                'sodium_per_serving' => 300.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            
            // Wat (Stews) - 15 items
            [
                'food_name' => 'Doro Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (240g)',
                'calories_per_serving' => 320.0,
                'protein_per_serving' => 28.0,
                'carbs_per_serving' => 10.0,
                'fat_per_serving' => 18.0,
                'fiber_per_serving' => 2.5,
                'sugar_per_serving' => 4.0,
                'sodium_per_serving' => 650.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Key Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (230g)',
                'calories_per_serving' => 290.0,
                'protein_per_serving' => 25.0,
                'carbs_per_serving' => 8.0,
                'fat_per_serving' => 17.0,
                'fiber_per_serving' => 2.0,
                'sugar_per_serving' => 3.5,
                'sodium_per_serving' => 600.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Yebeg Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (235g)',
                'calories_per_serving' => 310.0,
                'protein_per_serving' => 26.0,
                'carbs_per_serving' => 7.5,
                'fat_per_serving' => 19.0,
                'fiber_per_serving' => 2.2,
                'sugar_per_serving' => 3.0,
                'sodium_per_serving' => 620.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Dereq Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (220g)',
                'calories_per_serving' => 280.0,
                'protein_per_serving' => 22.0,
                'carbs_per_serving' => 9.0,
                'fat_per_serving' => 16.5,
                'fiber_per_serving' => 2.8,
                'sugar_per_serving' => 4.2,
                'sodium_per_serving' => 580.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Misir Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (220g)',
                'calories_per_serving' => 220.0,
                'protein_per_serving' => 12.0,
                'carbs_per_serving' => 30.0,
                'fat_per_serving' => 6.0,
                'fiber_per_serving' => 8.0,
                'sugar_per_serving' => 3.0,
                'sodium_per_serving' => 480.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Shiro Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (200g)',
                'calories_per_serving' => 180.0,
                'protein_per_serving' => 10.0,
                'carbs_per_serving' => 25.0,
                'fat_per_serving' => 5.0,
                'fiber_per_serving' => 6.0,
                'sugar_per_serving' => 2.5,
                'sodium_per_serving' => 420.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Kik Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (210g)',
                'calories_per_serving' => 200.0,
                'protein_per_serving' => 11.5,
                'carbs_per_serving' => 28.0,
                'fat_per_serving' => 5.5,
                'fiber_per_serving' => 7.5,
                'sugar_per_serving' => 3.2,
                'sodium_per_serving' => 450.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Atkilt Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (200g)',
                'calories_per_serving' => 120.0,
                'protein_per_serving' => 3.5,
                'carbs_per_serving' => 20.0,
                'fat_per_serving' => 3.5,
                'fiber_per_serving' => 5.0,
                'sugar_per_serving' => 8.0,
                'sodium_per_serving' => 380.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Gomen Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (150g)',
                'calories_per_serving' => 100.0,
                'protein_per_serving' => 5.0,
                'carbs_per_serving' => 8.0,
                'fat_per_serving' => 6.0,
                'fiber_per_serving' => 4.0,
                'sugar_per_serving' => 2.0,
                'sodium_per_serving' => 350.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Fasolia Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (180g)',
                'calories_per_serving' => 130.0,
                'protein_per_serving' => 6.0,
                'carbs_per_serving' => 18.0,
                'fat_per_serving' => 4.0,
                'fiber_per_serving' => 6.5,
                'sugar_per_serving' => 5.5,
                'sodium_per_serving' => 400.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Dinich Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (190g)',
                'calories_per_serving' => 160.0,
                'protein_per_serving' => 3.0,
                'carbs_per_serving' => 32.0,
                'fat_per_serving' => 2.5,
                'fiber_per_serving' => 4.0,
                'sugar_per_serving' => 3.0,
                'sodium_per_serving' => 420.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Tikel Gomen',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (170g)',
                'calories_per_serving' => 110.0,
                'protein_per_serving' => 4.0,
                'carbs_per_serving' => 16.0,
                'fat_per_serving' => 3.8,
                'fiber_per_serving' => 5.5,
                'sugar_per_serving' => 6.0,
                'sodium_per_serving' => 380.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Bozena Shiro',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (210g)',
                'calories_per_serving' => 250.0,
                'protein_per_serving' => 18.0,
                'carbs_per_serving' => 22.0,
                'fat_per_serving' => 9.0,
                'fiber_per_serving' => 6.5,
                'sugar_per_serving' => 3.5,
                'sodium_per_serving' => 520.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Yater Shiro',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (200g)',
                'calories_per_serving' => 190.0,
                'protein_per_serving' => 11.0,
                'carbs_per_serving' => 24.0,
                'fat_per_serving' => 5.5,
                'fiber_per_serving' => 7.0,
                'sugar_per_serving' => 3.0,
                'sodium_per_serving' => 450.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Yekik Wat',
                'brand' => 'Traditional',
                'category_id' => $categories['Wat (Stews)'],
                'serving_size' => '1',
                'serving_unit' => 'cup (205g)',
                'calories_per_serving' => 210.0,
                'protein_per_serving' => 12.0,
                'carbs_per_serving' => 29.0,
                'fat_per_serving' => 5.0,
                'fiber_per_serving' => 8.5,
                'sugar_per_serving' => 3.8,
                'sodium_per_serving' => 470.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            
            // Tibs - 10 items
            [
                'food_name' => 'Beef Tibs',
                'brand' => 'Traditional',
                'category_id' => $categories['Tibs'],
                'serving_size' => '1',
                'serving_unit' => 'serving (150g)',
                'calories_per_serving' => 280.0,
                'protein_per_serving' => 25.0,
                'carbs_per_serving' => 5.0,
                'fat_per_serving' => 18.0,
                'fiber_per_serving' => 1.5,
                'sugar_per_serving' => 2.0,
                'sodium_per_serving' => 520.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Lamb Tibs',
                'brand' => 'Traditional',
                'category_id' => $categories['Tibs'],
                'serving_size' => '1',
                'serving_unit' => 'serving (150g)',
                'calories_per_serving' => 310.0,
                'protein_per_serving' => 23.0,
                'carbs_per_serving' => 4.0,
                'fat_per_serving' => 23.0,
                'fiber_per_serving' => 1.0,
                'sugar_per_serving' => 1.5,
                'sodium_per_serving' => 480.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Awaze Tibs',
                'brand' => 'Traditional',
                'category_id' => $categories['Tibs'],
                'serving_size' => '1',
                'serving_unit' => 'serving (160g)',
                'calories_per_serving' => 300.0,
                'protein_per_serving' => 26.0,
                'carbs_per_serving' => 6.5,
                'fat_per_serving' => 19.0,
                'fiber_per_serving' => 1.8,
                'sugar_per_serving' => 3.0,
                'sodium_per_serving' => 550.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Zilzil Tibs',
                'brand' => 'Traditional',
                'category_id' => $categories['Tibs'],
                'serving_size' => '1',
                'serving_unit' => 'serving (170g)',
                'calories_per_serving' => 320.0,
                'protein_per_serving' => 28.0,
                'carbs_per_serving' => 4.0,
                'fat_per_serving' => 21.0,
                'fiber_per_serving' => 1.2,
                'sugar_per_serving' => 1.8,
                'sodium_per_serving' => 500.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Tibs Firfir',
                'brand' => 'Traditional',
                'category_id' => $categories['Tibs'],
                'serving_size' => '1',
                'serving_unit' => 'serving (200g)',
                'calories_per_serving' => 290.0,
                'protein_per_serving' => 18.0,
                'carbs_per_serving' => 25.0,
                'fat_per_serving' => 12.0,
                'fiber_per_serving' => 3.5,
                'sugar_per_serving' => 3.0,
                'sodium_per_serving' => 580.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Chicken Tibs',
                'brand' => 'Traditional',
                'category_id' => $categories['Tibs'],
                'serving_size' => '1',
                'serving_unit' => 'serving (140g)',
                'calories_per_serving' => 240.0,
                'protein_per_serving' => 27.0,
                'carbs_per_serving' => 4.5,
                'fat_per_serving' => 12.0,
                'fiber_per_serving' => 1.5,
                'sugar_per_serving' => 2.5,
                'sodium_per_serving' => 520.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Fish Tibs',
                'brand' => 'Traditional',
                'category_id' => $categories['Tibs'],
                'serving_size' => '1',
                'serving_unit' => 'serving (130g)',
                'calories_per_serving' => 200.0,
                'protein_per_serving' => 25.0,
                'carbs_per_serving' => 3.0,
                'fat_per_serving' => 9.0,
                'fiber_per_serving' => 1.0,
                'sugar_per_serving' => 1.5,
                'sodium_per_serving' => 450.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Vegetable Tibs',
                'brand' => 'Traditional',
                'category_id' => $categories['Tibs'],
                'serving_size' => '1',
                'serving_unit' => 'serving (180g)',
                'calories_per_serving' => 150.0,
                'protein_per_serving' => 6.0,
                'carbs_per_serving' => 18.0,
                'fat_per_serving' => 7.0,
                'fiber_per_serving' => 6.0,
                'sugar_per_serving' => 8.0,
                'sodium_per_serving' => 420.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Tibs with Rice',
                'brand' => 'Traditional',
                'category_id' => $categories['Tibs'],
                'serving_size' => '1',
                'serving_unit' => 'plate (350g)',
                'calories_per_serving' => 480.0,
                'protein_per_serving' => 30.0,
                'carbs_per_serving' => 55.0,
                'fat_per_serving' => 15.0,
                'fiber_per_serving' => 4.0,
                'sugar_per_serving' => 4.5,
                'sodium_per_serving' => 650.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Tibs with Injera',
                'brand' => 'Traditional',
                'category_id' => $categories['Tibs'],
                'serving_size' => '1',
                'serving_unit' => 'plate (300g)',
                'calories_per_serving' => 420.0,
                'protein_per_serving' => 28.0,
                'carbs_per_serving' => 40.0,
                'fat_per_serving' => 17.0,
                'fiber_per_serving' => 5.0,
                'sugar_per_serving' => 3.0,
                'sodium_per_serving' => 620.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            
            // Kitfo - 5 items
            [
                'food_name' => 'Kitfo',
                'brand' => 'Traditional',
                'category_id' => $categories['Kitfo'],
                'serving_size' => '1',
                'serving_unit' => 'serving (120g)',
                'calories_per_serving' => 380.0,
                'protein_per_serving' => 25.0,
                'carbs_per_serving' => 2.0,
                'fat_per_serving' => 30.0,
                'fiber_per_serving' => 0.5,
                'sugar_per_serving' => 0.5,
                'sodium_per_serving' => 420.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Gored Gored',
                'brand' => 'Traditional',
                'category_id' => $categories['Kitfo'],
                'serving_size' => '1',
                'serving_unit' => 'serving (130g)',
                'calories_per_serving' => 350.0,
                'protein_per_serving' => 28.0,
                'carbs_per_serving' => 1.5,
                'fat_per_serving' => 26.0,
                'fiber_per_serving' => 0.3,
                'sugar_per_serving' => 0.4,
                'sodium_per_serving' => 400.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Kitfo with Ayib',
                'brand' => 'Traditional',
                'category_id' => $categories['Kitfo'],
                'serving_size' => '1',
                'serving_unit' => 'serving (150g)',
                'calories_per_serving' => 400.0,
                'protein_per_serving' => 28.0,
                'carbs_per_serving' => 4.0,
                'fat_per_serving' => 31.0,
                'fiber_per_serving' => 0.8,
                'sugar_per_serving' => 1.5,
                'sodium_per_serving' => 450.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Kitfo with Kocho',
                'brand' => 'Traditional',
                'category_id' => $categories['Kitfo'],
                'serving_size' => '1',
                'serving_unit' => 'serving (200g)',
                'calories_per_serving' => 420.0,
                'protein_per_serving' => 22.0,
                'carbs_per_serving' => 35.0,
                'fat_per_serving' => 22.0,
                'fiber_per_serving' => 5.0,
                'sugar_per_serving' => 2.0,
                'sodium_per_serving' => 380.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Leb Leb',
                'brand' => 'Traditional',
                'category_id' => $categories['Kitfo'],
                'serving_size' => '1',
                'serving_unit' => 'serving (110g)',
                'calories_per_serving' => 320.0,
                'protein_per_serving' => 26.0,
                'carbs_per_serving' => 2.5,
                'fat_per_serving' => 23.0,
                'fiber_per_serving' => 0.6,
                'sugar_per_serving' => 0.7,
                'sodium_per_serving' => 390.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            
            
            // Vegetarian Dishes - 10 items
            [
                'food_name' => 'Azifa',
                'brand' => 'Traditional',
                'category_id' => $categories['Vegetarian Dishes'],
                'serving_size' => '1',
                'serving_unit' => 'cup (180g)',
                'calories_per_serving' => 220.0,
                'protein_per_serving' => 12.0,
                'carbs_per_serving' => 35.0,
                'fat_per_serving' => 4.0,
                'fiber_per_serving' => 9.0,
                'sugar_per_serving' => 3.5,
                'sodium_per_serving' => 380.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            [
                'food_name' => 'Buticha',
                'brand' => 'Traditional',
                'category_id' => $categories['Vegetarian Dishes'],
                'serving_size' => '1',
                'serving_unit' => 'cup (150g)',
                'calories_per_serving' => 250.0,
                'protein_per_serving' => 10.0,
                'carbs_per_serving' => 25.0,
                'fat_per_serving' => 12.0,
                'fiber_per_serving' => 6.0,
                'sugar_per_serving' => 4.0,
                'sodium_per_serving' => 320.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            // ... continue with more vegetarian dishes
            
            // Side Dishes - 10 items
            [
                'food_name' => 'Ayib',
                'brand' => 'Traditional',
                'category_id' => $categories['Side Dishes'],
                'serving_size' => '0.5',
                'serving_unit' => 'cup (60g)',
                'calories_per_serving' => 80.0,
                'protein_per_serving' => 6.0,
                'carbs_per_serving' => 1.5,
                'fat_per_serving' => 5.5,
                'fiber_per_serving' => 0.0,
                'sugar_per_serving' => 1.0,
                'sodium_per_serving' => 120.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            // ... continue with more side dishes
            
            // Traditional Breakfast - 10 items
            [
                'food_name' => 'Ful',
                'brand' => 'Traditional',
                'category_id' => $categories['Traditional Breakfast'],
                'serving_size' => '1',
                'serving_unit' => 'cup (250g)',
                'calories_per_serving' => 250.0,
                'protein_per_serving' => 12.0,
                'carbs_per_serving' => 35.0,
                'fat_per_serving' => 6.0,
                'fiber_per_serving' => 10.0,
                'sugar_per_serving' => 2.0,
                'sodium_per_serving' => 450.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            // ... continue with more breakfast items
            
            // Beverages - 10 items
            [
                'food_name' => 'Tej',
                'brand' => 'Traditional',
                'category_id' => $categories['Beverages'],
                'serving_size' => '1',
                'serving_unit' => 'glass (150ml)',
                'calories_per_serving' => 180.0,
                'protein_per_serving' => 0.5,
                'carbs_per_serving' => 15.0,
                'fat_per_serving' => 0.0,
                'fiber_per_serving' => 0.0,
                'sugar_per_serving' => 14.0,
                'sodium_per_serving' => 10.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            // ... continue with more beverages
            
            // Legume-Based Dishes - 10 items
            [
                'food_name' => 'Kik Alicha',
                'brand' => 'Traditional',
                'category_id' => $categories['Legume-Based Dishes'],
                'serving_size' => '1',
                'serving_unit' => 'cup (200g)',
                'calories_per_serving' => 190.0,
                'protein_per_serving' => 11.0,
                'carbs_per_serving' => 28.0,
                'fat_per_serving' => 4.5,
                'fiber_per_serving' => 8.5,
                'sugar_per_serving' => 3.0,
                'sodium_per_serving' => 400.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            // ... continue with more legume-based dishes
            
            // Vegetable Dishes - 10 items
            [
                'food_name' => 'Yeabesha Gomen',
                'brand' => 'Traditional',
                'category_id' => $categories['Vegetable Dishes'],
                'serving_size' => '1',
                'serving_unit' => 'cup (150g)',
                'calories_per_serving' => 90.0,
                'protein_per_serving' => 5.5,
                'carbs_per_serving' => 10.0,
                'fat_per_serving' => 4.0,
                'fiber_per_serving' => 5.0,
                'sugar_per_serving' => 3.0,
                'sodium_per_serving' => 350.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            // ... continue with more vegetable dishes
            
            // Snacks & Appetizers - 10 items
            [
                'food_name' => 'Kolo',
                'brand' => 'Traditional',
                'category_id' => $categories['Snacks & Appetizers'],
                'serving_size' => '0.5',
                'serving_unit' => 'cup (50g)',
                'calories_per_serving' => 200.0,
                'protein_per_serving' => 7.0,
                'carbs_per_serving' => 30.0,
                'fat_per_serving' => 6.0,
                'fiber_per_serving' => 5.0,
                'sugar_per_serving' => 1.0,
                'sodium_per_serving' => 10.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            // ... continue with more snacks
            
            // Holiday & Special Occasion - 10 items
            [
                'food_name' => 'Doro Wat (Holiday Version)',
                'brand' => 'Traditional',
                'category_id' => $categories['Holiday & Special Occasion'],
                'serving_size' => '1',
                'serving_unit' => 'cup (250g)',
                'calories_per_serving' => 350.0,
                'protein_per_serving' => 30.0,
                'carbs_per_serving' => 12.0,
                'fat_per_serving' => 20.0,
                'fiber_per_serving' => 3.0,
                'sugar_per_serving' => 5.0,
                'sodium_per_serving' => 700.0,
                'is_verified' => true,
                'is_public' => true,
            ],
            // ... continue with more holiday foods
        ];

        // Insert all food items
        foreach ($foodItems as $item) {
            DB::table('food_items')->insert(array_merge($item, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}